import UIKit
import Capacitor
import WebKit

/// Forces mobile Safari layout/UA behavior so the remote Next.js app
/// uses phone breakpoints instead of a zoomed-out desktop layout.
class MobileBridgeViewController: CAPBridgeViewController {
  override open func webViewConfiguration(for instanceConfiguration: InstanceConfiguration) -> WKWebViewConfiguration {
    let configuration = super.webViewConfiguration(for: instanceConfiguration)
    configuration.defaultWebpagePreferences.preferredContentMode = .mobile
    return configuration
  }

  override open func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    webView?.scrollView.contentInsetAdjustmentBehavior = .never
    if let preferences = webView?.configuration.defaultWebpagePreferences {
      preferences.preferredContentMode = .mobile
    }
  }

  /// Plugins that live in THIS app target have to be registered by hand.
  ///
  /// Capacitor does NOT scan the binary for `@objc` plugin classes — `registerPlugins()` in
  /// CapacitorBridge only walks `packageClassList` from `capacitor.config.json` and calls
  /// `NSClassFromString` on each entry. That list is generated by `cap sync` from the npm
  /// `@capacitor/*` packages, so an app-local plugin never appears in it and is never loaded.
  /// `Capacitor.isPluginAvailable("…")` then answers false in JS and every call rejects.
  ///
  /// That silently cost us twice:
  ///   - AppleVision (AJA-273) fell back to the imgly WASM engine on every cutout, which looks
  ///     identical to success because `cutout()` degrades on purpose. Confirmed by the
  ///     `cutoutEngine: imgly@1.7.0` stamp on an item added after the engine was switched on.
  ///   - SharedInbox (AJA-201) has never been reachable, so shared IMAGES could not arrive. The
  ///     shared-link path works because it rides the deep-link query instead of this plugin.
  ///
  /// `registerPluginInstance` is the right call, not `registerPluginType` — the latter returns
  /// early whenever `autoRegisterPlugins` is true, which it is here.
  ///
  /// Adding these classes to `packageClassList` would work until the next `cap sync` overwrote
  /// the file. This survives it.
  override open func capacitorDidLoad() {
    super.capacitorDidLoad()
    bridge?.registerPluginInstance(AppleVisionPlugin())
    bridge?.registerPluginInstance(SharedInboxPlugin())
  }
}
